### ISSUE TITLE
IndexOutOfRangeException while running default scenario

### ISSUE THREAD

**Issue by giacomodeliberali** [Azure/azure-signalr-bench#96]
Hi, I just installed the tool in my Windows pc using 

```
dotnet tool install --global Microsoft.dotnet-signalr-benchmark --version 1.0.56301
```

but as soon as I start the test I got this exception that prevents the test to continue. 

```
2021-04-30 17:11:30.162 +02:00 [ERR] System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Plugin.Microsoft.Azure.SignalR.Benchmark.SignalRUtils.Percentile(Int32[] sequence, Double excelPercentile) in C:\Users\giacomo.deliberali\Desktop\azure-signalr-bench-master\src\signalr\Utils\SignalRUtils.cs:line 886
   at Plugin.Microsoft.Azure.SignalR.Benchmark.SignalRUtils.<>c__DisplayClass48_0.<MergeConnectionStatistics>b__0(Double i) in C:\Users\giacomo.deliberali\Desktop\azure-signalr-bench-master\src\signalr\Utils\SignalRUtils.cs:line 847
   at System.Linq.Enumerable.SelectArrayIterator`2.MoveNext()
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
   at Plugin.Microsoft.Azure.SignalR.Benchmark.SignalRUtils.MergeConnectionStatistics(IDictionary`2[] results, Double[] percentileList) in C:\Users\giacomo.deliberali\Desktop\azure-signalr-bench-master\src\signalr\Utils\SignalRUtils.cs:line 846
   at Plugin.Microsoft.Azure.SignalR.Benchmark.MasterMethods.CollectStatisticBase.ConnectionStatEventerCallback(IDictionary`2 stepParameters, IDictionary`2 pluginParameters, IList`1 clients) in C:\Users\giacomo.deliberali\Desktop\azure-signalr-bench-master\src\signalr\MasterMethods\CollectStatisticBase.cs:line 121
   at Plugin.Microsoft.Azure.SignalR.Benchmark.MasterMethods.CollectStatisticBase.<>c__DisplayClass11_0.<<CollectStatistics>b__0>d.MoveNext() in C:\Users\giacomo.deliberali\Desktop\azure-signalr-bench-master\src\signalr\MasterMethods\CollectStatisticBase.cs:line 78
```

Are there any other tool versions to try out?

**Comment by bjqian** [comment]
Close this issue as **version 1** is deprecated.
